steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/audiogram', '.']
images: ['gcr.io/$PROJECT_ID/audiogram']
timeout: 1260s
